[package]
name = "zync"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
better-panic = "0.3.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
derive_setters = "0.1.6"
dialoguer = "0.11.0"
dirs = "5.0.1"
human-panic = "2.0.2"
itertools = "0.13.0"
libc = "0.2.161"
lipsum = "0.9.1"
log = "0.4.22"
nanoid = "0.4.0"
once_cell = "1.20.2"
open = "5.3.0"
rand = "0.8.5"
ratatui = "0.29.0"
reqwest = "0.12.8"
serde = "1.0.213"
serde_json = "1.0.132"
strip-ansi-escapes = "0.2.0"
strum = "0.26.3"
style = "0.1.0"
tailwind = "0.1.0"
tokio ={version="1.41.0", features=["full"]} 
tui-big-text = "0.7.0"
tui-logger = "0.13.2"
tui-textarea = "0.7.0"
tui_confirm_dialog = "0.2.3"
unicode-width = "0.2.0"
whoami = "1.5.2"

[patch.crates-io]
tui-logger = { git = "https://github.com/gin66/tui-logger.git"}
tui_confirm_dialog = { git = "https://github.com/urizennnn/tui-confirm-dialog.git",branch="bump/crate-versions"}
