[package]
name = "zync"
description = "An advanced CLI tool for transferring files through your terminal."
authors = ["urizennnn"]
license = "MIT"
readme = "README.md"
version = "0.0.1-alpha"
keywords = ["cli", "file-transfer", "zync"]
edition = "2021"

[workspace]
members = [
    "lib_tcp"
]

[dependencies]
better-panic = "0.3.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
derive_setters = "0.1.6"
dialoguer = "0.11.0"
dirs = "5.0.1"
human-panic = "2.0.2"
itertools = "0.14.0"
libc = "0.2.161"
lipsum = "0.9.1"
nanoid = "0.4.0"
open = "5.3.0"
rand = "0.8.5"
ratatui = "0.29.0"
reqwest = "0.12.9"
strip-ansi-escapes = "0.2.0"
strum = "0.26.3"
style = "0.1.0"
tailwind = "0.1.0"
tui-big-text = "0.7.0"
tui-logger = "0.14.0"
tui-textarea = "0.7.0"
tui_confirm_dialog = "0.2.4"
unicode-width = "0.2.0"

# Shared dependencies for all workspace members
[dependencies.lib_tcp]
path = "./lib_tcp"

[dependencies.once_cell]
version = "1.20.2"

[dependencies.serde]
version = "1.0.214"

[dependencies.serde_json]
version = "1.0.132"

[dependencies.whoami]
version = "1.5.2"

[dependencies.tokio]
version = "1.41.0"
features = ["full"]

[dependencies.log]
version = "0.4.22"

